---
title: "Publications"
---

#### Published articles

1. Aguirre-Gutiérrez, J.; Díaz, S.; Rifai, S. W.; Corral-Rivas, J. J.; Nava-Miranda, M. G.; González-M, R.; Hurtado-M, A. B.; Revilla, N. S.; Vilanova, E.; Almeida, E.; de Oliveira, E. A.; Alvarez-Davila, E.; Alves, L. F.; de Andrade, A. C. S.; Lola da Costa, A. C.; Vieira, S. A.; Aragão, L.; Arets, E.; Aymard C., G. A.; **Kamimura, V. de A.**; et al. (2025). Tropical forests in the Americas are changing too slowly to track climate change. *Science*, 387, 1–11.

2. Sabino, G. P.; Pinheiro, F.; Cabral, J. S.; Koch, I.; Marcusso, G. M.; Tavares, M. M.; Cunha, I. M.; **Kamimura, V. de A.** (2025). Islanded islands: dual isolation drives distinctive and threatened floras of Neotropical maritime inselbergs. *Journal of Vegetation Science*, 1, 1.

3. Sabino, G. P.; **Kamimura, V. de A.**; Marcusso, G. M.; Koch, I.; Pinheiro, F. (2025). Rediscovery and conservation of (Begoniaceae): a critically endangered, insular, narrow endemic species of Brazil. *Oryx*, 59, 1–5.

4. **Kamimura, V. de A.**; Loiola, P. de P.; Neves, D. R. de M.; Marcusso, G. M.; Sabino, G. P.; Assis, M. A.; Joly, C. A.; Pinheiro, F. (2025). Unveiling anthropogenic disturbance effects on tropical tree communities: clade-based insights across elevations. *Trees, Forests and People*, 1, 100894.

5. Sachetti, W. L.; **Kamimura, V. de A.**; Mayer, J. L. S.; Arida, B. L.; de Lima, T. M.; Graciano, D. S.; Pinheiro, F. (2025). We are not all the same: the role of intrapopulation trait variability in shaping functional strategy and performance of widespread species. *Plant Diversity*, 48, 1–31.

6. Sabino, G. P.; Pinheiro, F.; Koch, I.; de Azevedo, M. L.; Tavares, M. M.; Francini, C. L. B.; Trotta, G. N.; Cunha, I. M.; Sabino, J.; Leite, K. L.; Pereira, R. A.; Pina, P. I.; **Kamimura, V. de A.** (2025). When natives become villains: plant super-dominance and its implications on island ecosystems. *Cell Reports Sustainability*, 2, 100434.

7. Bialic-Murphy, L.; McElderry, R. M.; Esquivel-Muelbert, A.; van den Hoogen, J.; Zuidema, P. A.; Phillips, O. L.; de Oliveira, E. A.; Loayza, P. A.; Alvarez-Davila, E.; Alves, L. F.; Maia, V. A.; Vieira, S. A.; Arantes da Silva, L. C.; Araujo-Murakami, A.; Arets, E.; Astigarraga, J.; Baccaro, F.; Baker, T.; Banki, O.; **Kamimura, V. de A.**; et al. (2024). The pace of life for forest trees. *Science*, 386, 92–98.

8. Hughes, A. C.; Tougeron, K.; Martin, D. A.; Menga, F.; Rosado, B. H. P.; Villasante, S.; Madgulkar, S.; Gonçalves, F.; Geneletti, D.; Diele-Viegas, L. M.; Berger, S.; Colla, S. R.; **Kamimura, V. de A.**; Caggiano, H.; Melo, F.; de Oliveira Dias, M. G.; Kellner, E.; do Couto, E. V. (2023). Smaller human populations are neither a necessary nor sufficient condition for biodiversity conservation. *Biological Conservation*, 277, 109841.

9. Hughes, A. C.; Tougeron, K.; Martin, D. A.; Menga, F.; Rosado, B. H. P.; Villasante, S.; Madgulkar, S.; Gonçalves, F.; Diele-Viegas, L. M.; Colla, S. R.; **Kamimura, V. de A.**; Caggiano, H.; Melo, F.; de Oliveira Dias, M. G.; Kellner, E.; do Couto, E. V. (2023). Smaller human populations are still not a necessary condition for biodiversity conservation: a response to Cafaro et al. (2023). *Biological Conservation*, 282, 110053.

10. Loiola, P. P.; Morellato, L. P. C.; Camargo, M. G. G.; **Kamimura, V. de A.**; Mattos, J. S.; Streher, A. S.; Le Stradic, S. (2023). Shared role of vegetation types, elevation and soil affecting plant diversity in an old-tropical mountain hotspot. *Journal of Mountain Science*, 20, 1842–1853.

11. **Kamimura, V. de A.**; Loiola, P. P.; Carmona, C. P.; Assis, M. A.; Joly, C. A.; Santos, F. A. M.; Vieira, S. A.; Alves, L. F.; Martins, V. F.; Ramos, E.; Ramos, R.; de Bello, F. (2023). Trait interactions effects on tropical tree demography depend on the environmental context. *Perspectives in Plant Ecology, Evolution and Systematics*, 59, 125732.

12. Marcusso, G. M.; **Kamimura, V. de A.**; Borgiani, R.; Menini Neto, L.; Lombardi, J. A. (2022). Phytogeographic meta-analysis of the vascular epiphytes in the Neotropical region. *Botanical Review*, 1, 1–25.

13. **Kamimura, V. de A.**; Marcusso, G. M.; Sabino, G. P.; Assis, M. A.; Joly, C. A.; de Paula Loiola, P. (2022). Family legacy: contrasting diversity–elevation relationships in a coastal Atlantic Forest mountain system. *Plant Ecology*, 223, 1–17.

14. Blundo, C.; Carilla, J.; Grau, R.; Malizia, A.; Malizia, L.; Osinaga-Acosta, O.; Bird, M.; Bradford, M.; Catchpole, D.; Ford, A.; Graham, A.; Hilbert, D.; Kemp, J.; Laurance, S.; Laurance, W.; Ishida, F. Y.; Marshall, A.; Waite, C.; Woell, H.; **Kamimura, V. de A.**; et al. (2021). Taking the pulse of Earth's tropical forests using networks of highly distributed plots. *Biological Conservation*, 260, 108849.

15. Sabino, G. P.; **Kamimura, V. de A.**; Borgiani, R.; Konopczyk, R.; Dickfeldt, E. P.; Bertoni, J. E. A.; Evangelista, S. A. S.; Marcusso, G. M. (2021). The vascular flora of Porto Ferreira State Park: an ecotonal area in São Paulo State, southeastern Brazil. *Biota Neotropica*, 21, 1–29.

16. Sabino, G. P.; **Kamimura, V. de A.**; Marcusso, G. M.; Monteiro, R. (2021). Atlantic Forest meets the Cerrado: floristic, structure and species distribution of an ecotonal tree community. *Nativa*, 9, 471–480.

17. Marcusso, G. M.; **Kamimura, V. de A.**; Monteiro, R. (2019). Epiphyte–phorophyte relationships: assessing the differences between seasonal semideciduous and swamp forests in southeastern Brazil. *Hoehnea*, 46, 1–12.

18. Vargas, B. C.; Oliveira, A. P. C.; Udulutsch, R. G.; Marcusso, G. M.; Sabino, G. P.; Melo, P. H.; Grillo, R. M. M.; **Kamimura, V. de A.**; Assis, M. A. (2018). Climbing plants of Porto Ferreira State Park, southeastern Brazil. *Biota Neotropica*, 2, 1–9.

19. **Kamimura, V. de A.**; Morais, R. F.; Joly, C. A.; Assis, M. A. (2018). Floristic, structure and ecological groups of a tree community in the Atlantic rainforest at Serra do Mar, São Paulo, Brazil. *Nativa*, 6, 706.

20. **Kamimura, V. de A.**; Moraes, P. L. R.; Ribeiro, H. L.; Joly, C. A.; Assis, M. A. (2017). Tree diversity and elevational gradient: the case of Lauraceae in the Atlantic rainforest. *Flora*, 84–91.

21. **Kamimura, V. de A.**; Silva, V. F.; Assis, M. A. (2012). Structure and diversity of the Myrtaceae family in lowland ombrophilous dense forest of the State Park of Serra do Mar (Ubatuba, SP, Brazil). *Communications in Plant Sciences*, 2, 183–183.


